scan_matcher:
  ros__parameters:
    registration_method: "NDT"
    ndt_resolution: 2.0
    ndt_num_threads: 0
    trans_for_mapupdate: 1.5
    vg_size_for_input: 1.5
    vg_size_for_map: 0.075
    use_imu_rpy: false
    
graph_based_slam:
    ros__parameters:
      ndt_resolution: 1.5
      voxel_leaf_size: 0.2
      loop_detection_period: 3000
      threshold_loop_clousure_score: 1.5
      distance_loop_clousure: 30.0
      range_of_searching_loop_clousure: 30.0

