scan_matcher:
  ros__parameters:
    registration_method: "NDT"
    ndt_resolution: 2.0
    ndt_num_threads: 4
    trans_for_mapupdate: 1.5
    vg_size_for_input: 1.5
    vg_size_for_map: 0.075
    vg_size_for_viz: 0.08
    use_imu: false
    use_gravity_correction: true