scan_matcher:
  ros__parameters:
    registration_method: "NDT"
    ndt_resolution: 1.5
    ndt_num_threads: 4
    trans_for_mapupdate: 1.5
    vg_size_for_input: 1.0
    vg_size_for_map: 0.075
    use_imu_rpy: false
    use_imu_posatt: false
    use_gravity_correction: true